project:
  type: website

website:
  title: "ff-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - keepers.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

